version: "3"

services:
  redis:
    image: redis:4.0.8
    restart: always
    logging:
      driver: gcplogs

  app:
    build: ./src/app
    restart: always
    environment:
      - FLAG=TSGCTF{uo_uo_uo_uo_uoooooooo_uo_no_gawa_love}
      - ADMIN_UID=rRugPOZEgZ
    logging:
      driver: gcplogs

  nginx:
    build: ./src/nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/nginx/supervisord.conf:/etc/supervisord.conf:ro
      - ./tcpdump/:/var/lib/tcpdump
    restart: always
    environment:
      TCPDUMP_ENABLE: "true"
      CTF_PORT: 80
    logging:
      driver: gcplogs

  worker:
    build: ./src/worker
    depends_on:
      - redis
    restart: always
    environment:
      - ADMIN_UID=rRugPOZEgZ
    logging:
      driver: gcplogs
